
import React from "react";
import {
  DEFAULT_SETTINGS,
  COLOR_OPTION_MAP,
  normalizeHexColor,
  normalizeSettings,
  loadImage,
  drawImageCover,
  getTextFont,
  getTitleFont,
  getTitleFontMedium,
  trimTextToWidth,
  wrapText,
  drawAdaptiveMultiline,
  drawCornerTriangle,
  drawSquarePattern,
  drawLogo,
  drawDate,
  drawImageFrameClassic,
  drawBottomLinkStrip,
  drawSubtleGrid,
  drawFooterMeta,
  drawSocialStrip,
  drawAdBar,
  drawClassicFormat,
  drawSplitFormat,
  drawMarketFormat,
  drawMagazineFormat,
  drawFrameFormat
} from "./borbila_v2_engine.js";

export const BORBILA_PRESETS = {
  "classic-red": {
    id: "classic-red",
    label: "অ্যাঙ্গেল্ড রেড নিউজ কার্ড",
    labelEn: "Angled Red News Card",
    description: "লোগো ও তারিখ হেডার, কোণাকুণি ছবির ফ্রেম, গাঢ় লাল হেডলাইন প্যানেল এবং বটম সিটিএ ফুটার।",
    primary_color: "#d60000",
    secondary_color: "#7a0000",
    accent_color: "#ff2d2d",
    top_background_color: "#fff0f0",
    title_color: "#ffffff",
    date_color: "#3f3f46",
    text_color: "#181818",
    logo_color: "#181818",
    badge: "জনপ্রিয়"
  },
  "fresh-blue": {
    id: "fresh-blue",
    label: "হোয়াইট এডিটোরিয়াল কার্ড",
    labelEn: "White Editorial Card",
    description: "বড় আকারের শীর্ষ ছবি, পরিচ্ছন্ন সাদা হেডলাইন এলাকা, বটম তারিখ ও ওয়েবসাইট স্ট্রিপ।",
    primary_color: "#d32929",
    secondary_color: "#e6e6e6",
    accent_color: "#f44336",
    top_background_color: "#f3f3f3",
    title_color: "#202020",
    date_color: "#555555",
    text_color: "#202020",
    logo_color: "#d32929",
    badge: "ক্লিন"
  },
  "green-market": {
    id: "green-market",
    label: "ডার্ক ব্রেকিং নিউজ কার্ড",
    labelEn: "Dark Breaking News",
    description: "ডার্ক রেড ব্রেকিং-নিউজ হেডার, আধুনিক ফটো কাটআউট, সিটিএ পিল এবং বটম অ্যাড/ইউআরএল এরিয়া।",
    primary_color: "#e50914",
    secondary_color: "#050000",
    accent_color: "#ff3232",
    top_background_color: "#130000",
    title_color: "#ffffff",
    date_color: "#ffffff",
    text_color: "#ffffff",
    logo_color: "#ffffff",
    badge: "ব্রেকিং"
  },
  "dark-magazine": {
    id: "dark-magazine",
    label: "সোশাল ফুটার টিভি কার্ড",
    labelEn: "Social Footer TV Card",
    description: "টপ ফটো, স্ট্রং রেড টাইটেল প্যানেল, সোশাল মিডিয়া ইউআরএল স্ট্রিপ ও অ্যাডভার্টাইজ বার।",
    primary_color: "#b40000",
    secondary_color: "#6c0000",
    accent_color: "#ffffff",
    top_background_color: "#ffffff",
    title_color: "#ffffff",
    date_color: "#ffffff",
    text_color: "#ffffff",
    logo_color: "#ffffff",
    badge: "সোশাল"
  },
  "gold-frame": {
    id: "gold-frame",
    label: "রেড ক্যাপশন স্কয়ার ফ্রেম",
    labelEn: "Red Caption Square",
    description: "শীর্ষে ফুল ছবি, সেন্ট্রাল লোগো ব্যাজ, ডিপ রেড হেডলাইন এরিয়া এবং গোল্ডেন সিটিএ/লিঙ্ক।",
    primary_color: "#cf0000",
    secondary_color: "#530000",
    accent_color: "#ffef00",
    top_background_color: "#080000",
    title_color: "#ffffff",
    date_color: "#ffffff",
    text_color: "#ffffff",
    logo_color: "#ffffff",
    badge: "ফ্রেম"
  }
};
